As part of this release we had [2 commits](https://github.com/TestUser/FakeRepository/commits/1.2.3) which resulted in [1 issue](https://github.com/gep13/FakeRepository/issues?q=milestone%3A1.2.3?closed=1) being closed.

__Bug__

- [__#6__](http://example.com/6) Issue 6

### I am a header

I am content
