As part of this release we had [1 commit](https://github.com/TestUser/FakeRepository/commits/1.2.3) which resulted in [1 issue](https://github.com/gep13/FakeRepository/issues?q=milestone%3A1.2.3?closed=1) being closed.

__Foo__

- [__#1__](http://example.com/1) Issue 1
